//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YahooScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestSharpStock
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string Symbol { get; set; }
        public string Change { get; set; }
        public string MarketTime { get; set; }
        public string ChgPct { get; set; }
        public string Price { get; set; }
        public string Closing { get; set; }
        public string Method { get; set; }
    }
}
